### ISSUE TITLE
Arm Away/Stay

### ISSUE THREAD

**Issue by ghost** [Mavrrick/ADT-Tools-2#4]
hello 

I noticed a few days ago that the arm away and stay no longer can control the ADT alarm was this a result of the changes that happened 7 days ago?

**Comment by ChuckClasik** [comment]
Same here, only one that works is disarm. Any help appreciated..

**Comment by ssandovalb** [comment]
I was able to get mine working again, it seems it was unpublished. All you got to do is go to your smart apps in SmartThings and publish the Adt tools 2

**Comment by ChuckClasik** [comment]
I’ve done that. But will try it again. Missing ADT Tools!!

**Comment by Raiderjb** [comment]
Please help I don't understand how to do this 'update'/button reset. I have ADT Tools but have this button problem and need to do the suggested update.

BTW, my ADT tools is already published in Smartthings.

Please can you give me a step by step on updating/adding the reset in Smartthings.

Thank you,

**Comment by ChuckClasik** [comment]
Nothing I’ve done including recreating the buttons, has helped with it in
the New SmartThings app. I’m assuming there will need to be an update.

**Comment by Raiderjb** [comment]
This the update it just needs to get into/update the 'code', I don't see how to do that in smartthings...

UPDATE>>>>> Here is what I did or didn't do... kept clicking on this link, 
"update to reset flag for button creation", in the 'code' tab above, which didn't really help me until I figured it out... click on this in the 'code' tab, the source code... "adt-tools-2.src" <<<< Just copy EVERYTHING and past it over your ADT Tools code in Smartthings. 

Then SAVE and Publish to yourself (For ME), not sure if required but I restarted my phone and NOW IT WORKS AGAIN!!!

CRAIG ... THANK YOU FOR THE UPDATE!!! LIFESAVER

**Comment by ragenstorm** [comment]
> kept clicking on this link,
> "update to reset flag for button creation", in the 'code' tab above,

Raiderjib you said " kept clicking on this link,
"update to reset flag for button creation", in the 'code' tab above,"

where is this link at? is it ongroovy IDE or the app on your phone ?

**Comment by ghost** [comment]
I got mine to work just had to delete the tiles and let adt tools create them. All good now

**Comment by ragenstorm** [comment]
so just delete the tiles that tiles that I created myself and just use the button  that came with the home security on the dashboard page ? ( i have the adt/smartthin hub )

**Comment by ChuckClasik** [comment]
I’ve done that as well. Note that I’m using the new smartthings app. Still
works in classic. I got a few emails saying that classic is End Of Life.
Just won’t work in the New App.
